---
title: FBI Crime Data Challenge
format: 
  dashboard:
    orientation: rows
    nav-buttons: [github]
    theme: lux
    github: https://github.com/kszeng/Tidy-Tuesday
logo: images/US-FBI-BWSeal.svg
logo-alt: FBI logo black and white
---

```{r}
knit_print.integer = function(x, ...) {
  prettyNum(x, big.mark=",")
}

registerS3method(
  "knit_print", "integer", knit_print.integer,
  envir = asNamespace("knitr")
)


```

```{r}
#===SETUP===

r = getOption("repos")
r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)

# install.packages("bsicons")

# load libraries
library(skimr)
library(DataExplorer)
library(ggplot2)
library(ggExtra)
library(dplyr)
library(scales)
library(ggpubr)
library(tidyverse)
library(tidytext)
library(quarto)
library(bsicons)

# load and clean original dataset
agencies <- tidytuesdayR::tt_load(2025, week = 7)$agencies

# ---us-level map: data wrangling---
library(usmap)
library(tigris)
library(cdlTools)

# create data frame for mapping across states
usmap_df <- agencies %>% group_by(state_abbr) %>% 
  summarise(value = n()) %>% 
  rename("state" = "state_abbr")

# create data fram for mapping across counties
counties_df <- agencies %>% group_by(county) %>% 
  summarise(value = n()) %>% 
  rename("fips" = "county")

# ---county-level map: data wrangling---

# zoom in on the two most represented states and plot by county
fips_codes <- fips_codes %>% mutate(county = toupper(str_remove_all(county, pattern = " County")))

# create column containing FIPS codes for counties
state_merge <- merge(agencies, 
                  unique(fips_codes %>% select(state, state_code)),
                  by.x = "state_abbr", 
                  by.y = "state", 
                  all.x = TRUE)

state_merge <- merge(state_merge,
                     unique(fips_codes %>% select(county, county_code)),
                     by.x = "county",
                     by.y = "county")

state_merge$fips <- paste(state_merge$state_code, state_merge$county_code, sep = "")

state_merge <- state_merge[!duplicated(state_merge$agency_name),]

# summarise by fips codes
fips_counts <- state_merge %>% group_by(fips) %>% 
  summarise(value = n()) %>% 
  arrange(desc(value))


```
```{r}
# calculate values for value boxes

# total participating agencies across the U.S
num_agencies <- length(unique(agencies[["agency_name"]]))

# proportion NIBRS participation
nibrs_prop <- as.integer(sum(agencies$is_nibrs, na.rm = T)/nrow(agencies) * 100)

# count number of counties that participate
county_count <- length(unique(agencies$county))

# average number of agencies per state
state_avg <- as.integer(length(unique(agencies$agency_name))/length(unique(agencies$state)))

```

# Overview

## Row - Value boxes {height=20%}

:::{.valuebox icon="buildings" color="danger"}
Number of Agencies

`{r} num_agencies`
:::

:::{.valuebox icon="percent" color="dark"}
National NIBRS Participation

`{r} paste(nibrs_prop)`
:::

:::{.valuebox icon="buildings" color="danger"}
Participating Counties

`{r} county_count`
:::

:::{.valuebox icon="buildings" color="dark"}
Average Agencies per State

`{r} state_avg`
:::

## Row {height=80%}

### Column {.tabset width=60%}
```{r}
#| title: By State
# plot all states of the U.S. to create an empty map
plot_usmap(data = usmap_df, values = "value", regions = "states", color = "red") +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(250, 500, 750, 1000, 1250, 1500), 
                       limits = c(0, 1600)) +
  labs(title = "U.S. States",
       subtitle = "Distribution of Law Enforcement Agencies") +
  theme(legend.position = "right")

```

```{r}
#| title: By County
plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", linewidth = 0.05) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(10, 20, 30), 
                       limits = c(0, 40)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of Law Enforcement Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")

```

### Column {width=40%}

```{r}
#| label: tbl-types
#| tbl-cap: "Agency Types"
#| tbl-colwidths: [60, 40]

# number of each type of agency
type_summ <- agencies %>% filter(!(is.na(agency_type))) %>% 
  group_by(agency_type) %>% 
  summarise(count = n()) %>% 
  mutate(Frequency = paste(as.integer(count / sum(count) * 100), "%", sep = "")) %>% 
  rename("Agency Type" = agency_type,
         "Count" = count) %>% 
  arrange(desc(Count))

knitr::kable(type_summ, align = "c")
```

# By Region

## Row {}

### Column {.tabset width=70%}

```{r}
#| title: New England

# northeast
# connecticut, maine, massachusetts, new hampshire, rhode island, vermont,
# new jersey, new york, pennsylvania
plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", include = c("CT", "ME", "MA", "NH", "RI", "VT"), linewidth = 0.3) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(10, 20, 30, 40, 50), 
                       limits = c(0, 60)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of FBI Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")
```

```{r}
#| title: Middle Atlantic

plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", include = c("NJ", "NY", "PA"), linewidth = 0.3) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(10, 20, 30, 40, 50), 
                       limits = c(0, 60)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of FBI Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")
```

```{r}
#| title: East North Central Midwest

plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", include = c("IL", "IN", "MI", "OH", "WI"), linewidth = 0.3) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(5, 10, 15, 20), 
                       limits = c(0, 25)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of FBI Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")
```

```{r}
#| title: West North Central Midwest

plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", include = c("IA", "KS", "MN", "MO", "NE", "SD", "ND"), linewidth = 0.3) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(5, 10, 15), 
                       limits = c(0, 20)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of FBI Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")
```

```{r}
#| title: Atlantic South

plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", include = c("FL", "GA", "NC", "SC", "VA", "MD", "DE", 
            "DC", "WV"), linewidth = 0.2) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(5, 10), 
                       limits = c(0, 15)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of FBI Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")
```

```{r}
#| title: Central South

plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", include = c("AL", "KY", "MS", "TN",
            "AR", "LA", "OK", "TX"), linewidth = 0.2) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(5, 10), 
                       limits = c(0, 15)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of FBI Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")
```

```{r}
#| title: Mountain West

plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", include = c("AZ", "CO", "ID", "MT", "NV", "NM", "UT", "WY"), linewidth = 0.2) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(5, 10), 
                       limits = c(0, 15)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of FBI Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")
```

```{r}
#| title: Pacific West

plot_usmap(data = fips_counts, values = "value", regions = "counties", color = "red", include = c("AK", "CA", "HI", "OR", "WA"), linewidth = 0.2) +
  scale_fill_gradient2(low = "white", 
                       high = "red", 
                       name = "Number of Agencies", 
                       labels = scales::comma, 
                       breaks = c(5, 10), 
                       limits = c(0, 15)) + 
  labs(title = "U.S. Counties",
       subtitle = "Distribution of FBI Agencies") +
  theme(panel.background = element_blank(),
        legend.position = "right")
```

### Column {width=30%}

```{r}
#| label: tbl-states
#| tbl-cap: "Summary by State"
#| tbl-colwidths: [60, 40]

state_summ <- agencies %>% filter(!is.na(agency_type)) %>% 
  group_by(state) %>% 
  summarise(Count = n()) %>% 
  mutate(Frequency = paste(as.integer(Count / sum(Count) * 100), "%", sep = "")) %>% 
  rename("State" = state) %>% 
  arrange(desc(Count))

knitr::kable(state_summ, align = "c")
```